In [1]:
import numpy as np 
from scipy.io import arff
import pandas as pd

# Creating Training Data view

In [2]:
data1 = arff.loadarff('/Users/arslanaliawan/Desktop/Pre-experiment/Multivariate_arff/CharacterTrajectories/CharacterTrajectoriesDimension1_TRAIN.arff')

In [3]:
df_D1 = pd.DataFrame(data1[0])

In [4]:
data2 = arff.loadarff('/Users/arslanaliawan/Desktop/Pre-experiment/Multivariate_arff/CharacterTrajectories/CharacterTrajectoriesDimension2_TRAIN.arff')

In [5]:
df_D2 = pd.DataFrame(data2[0])

In [6]:
data3 = arff.loadarff('/Users/arslanaliawan/Desktop/Pre-experiment/Multivariate_arff/CharacterTrajectories/CharacterTrajectoriesDimension3_TRAIN.arff')

In [7]:
df_D3 = pd.DataFrame(data3[0])

In [8]:
df_D1.shape

(1422, 183)

In [9]:
df_D2.shape

(1422, 183)

In [10]:
df_D3.shape

(1422, 183)

In [11]:
df_D1.head(1)

channel_0_0  channel_0_1  channel_0_2  channel_0_3  channel_0_4  \
0     -0.13015    -0.183121    -0.234104    -0.279929    -0.321851   

   channel_0_5  channel_0_6  channel_0_7  channel_0_8  channel_0_9  ...  \
0    -0.363783      -0.4095    -0.460814    -0.517526     -0.57844  ...   

   channel_0_173  channel_0_174  channel_0_175  channel_0_176  channel_0_177  \
0            NaN            NaN            NaN            NaN            NaN   

   channel_0_178  channel_0_179  channel_0_180  channel_0_181  target  
0            NaN            NaN            NaN            NaN    b'1'  

[1 rows x 183 columns]

In [12]:
df_D1.target.unique()

array([b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9', b'10', b'11',
       b'12', b'13', b'14', b'15', b'16', b'17', b'18', b'19', b'20'],
      dtype=object)

In [13]:
df_D2.head(1)

channel_1_0  channel_1_1  channel_1_2  channel_1_3  channel_1_4  \
0     0.071323     0.083973     0.085534     0.078218     0.067093   

   channel_1_5  channel_1_6  channel_1_7  channel_1_8  channel_1_9  ...  \
0      0.05552     0.043275     0.027787     0.005932    -0.025043  ...   

   channel_1_173  channel_1_174  channel_1_175  channel_1_176  channel_1_177  \
0            NaN            NaN            NaN            NaN            NaN   

   channel_1_178  channel_1_179  channel_1_180  channel_1_181  target  
0            NaN            NaN            NaN            NaN    b'1'  

[1 rows x 183 columns]

In [14]:
df_D2.target.unique()

array([b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9', b'10', b'11',
       b'12', b'13', b'14', b'15', b'16', b'17', b'18', b'19', b'20'],
      dtype=object)

In [15]:
df_D3.head(1)

channel_2_0  channel_2_1  channel_2_2  channel_2_3  channel_2_4  \
0     0.899306     1.157239     1.320469     1.369472     1.323889   

   channel_2_5  channel_2_6  channel_2_7  channel_2_8  channel_2_9  ...  \
0     1.221704     1.098215     0.979016     0.880755     0.806413  ...   

   channel_2_173  channel_2_174  channel_2_175  channel_2_176  channel_2_177  \
0            NaN            NaN            NaN            NaN            NaN   

   channel_2_178  channel_2_179  channel_2_180  channel_2_181  target  
0            NaN            NaN            NaN            NaN    b'1'  

[1 rows x 183 columns]

In [16]:
df_D3.target.unique()

array([b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9', b'10', b'11',
       b'12', b'13', b'14', b'15', b'16', b'17', b'18', b'19', b'20'],
      dtype=object)

In [17]:
df_D1 = df_D1.fillna(0)
df_D2 = df_D2.fillna(0)
df_D3 = df_D3.fillna(0)

In [18]:
df_D1_T = df_D1.head(1).T

In [19]:
df_D2_T = df_D2.head(1).T

In [20]:
df_D3_T = df_D3.head(1).T

In [21]:
arr1 = df_D1_T.to_numpy()
arr2 = df_D2_T.to_numpy()
arr3 = df_D3_T.to_numpy()

In [22]:
finalarray_training_data = np.concatenate((arr1, arr2),axis=1)

In [23]:
finalarray_training_data = np.concatenate((finalarray_training_data, arr3),axis=1)

In [24]:
finalarray_training_data

array([[-0.13015, 0.071323, 0.899306],
       [-0.183121, 0.083973, 1.157239],
       [-0.234104, 0.085534, 1.320469],
       [-0.279929, 0.078218, 1.369472],
       [-0.321851, 0.067093, 1.323889],
       [-0.363783, 0.05552, 1.221704],
       [-0.4095, 0.043275, 1.098215],
       [-0.460814, 0.027787, 0.979016],
       [-0.517526, 0.005932, 0.880755],
       [-0.57844, -0.025043, 0.806413],
       [-0.642335, -0.066984, 0.742138],
       [-0.708369, -0.120483, 0.670647],
       [-0.776037, -0.185363, 0.589337],
       [-0.844799, -0.261646, 0.509148],
       [-0.913359, -0.349528, 0.440515],
       [-0.978872, -0.448135, 0.3894],
       [-1.036865, -0.554524, 0.359572],
       [-1.082398, -0.663956, 0.344563],
       [-1.111614, -0.770916, 0.322058],
       [-1.122168, -0.870061, 0.271962],
       [-1.112322, -0.95681, 0.199647],
       [-1.080184, -1.027564, 0.130489],
       [-1.024236, -1.079644, 0.084365],
       [-0.944604, -1.111149, 0.064815],
       [-0.843469, -1.121016, 0.0

In [25]:
finalarray_training_data[:][0]

array([-0.13015, 0.071323, 0.899306], dtype=object)

In [26]:
finalarray_training_data[:][-1]

array([b'1', b'1', b'1'], dtype=object)

In [27]:
dictionary = dict()

In [28]:
dictionary['1'] = finalarray_training_data

In [29]:
dictionary

{'1': array([[-0.13015, 0.071323, 0.899306],
        [-0.183121, 0.083973, 1.157239],
        [-0.234104, 0.085534, 1.320469],
        [-0.279929, 0.078218, 1.369472],
        [-0.321851, 0.067093, 1.323889],
        [-0.363783, 0.05552, 1.221704],
        [-0.4095, 0.043275, 1.098215],
        [-0.460814, 0.027787, 0.979016],
        [-0.517526, 0.005932, 0.880755],
        [-0.57844, -0.025043, 0.806413],
        [-0.642335, -0.066984, 0.742138],
        [-0.708369, -0.120483, 0.670647],
        [-0.776037, -0.185363, 0.589337],
        [-0.844799, -0.261646, 0.509148],
        [-0.913359, -0.349528, 0.440515],
        [-0.978872, -0.448135, 0.3894],
        [-1.036865, -0.554524, 0.359572],
        [-1.082398, -0.663956, 0.344563],
        [-1.111614, -0.770916, 0.322058],
        [-1.122168, -0.870061, 0.271962],
        [-1.112322, -0.95681, 0.199647],
        [-1.080184, -1.027564, 0.130489],
        [-1.024236, -1.079644, 0.084365],
        [-0.944604, -1.111149, 0.064815],
    

# Making Original Test View

In [30]:
Test_data1 = arff.loadarff('/Users/arslanaliawan/Desktop/Pre-experiment/Multivariate_arff/CharacterTrajectories/CharacterTrajectoriesDimension1_TEST.arff')

In [31]:
Test_df_D1 = pd.DataFrame(Test_data1[0])

In [32]:
Test_data2 = arff.loadarff('/Users/arslanaliawan/Desktop/Pre-experiment/Multivariate_arff/CharacterTrajectories/CharacterTrajectoriesDimension2_TEST.arff')

In [33]:
Test_df_D2 = pd.DataFrame(Test_data2[0])

In [34]:
Test_data3 = arff.loadarff('/Users/arslanaliawan/Desktop/Pre-experiment/Multivariate_arff/CharacterTrajectories/CharacterTrajectoriesDimension3_TEST.arff')

In [35]:
Test_df_D3 = pd.DataFrame(Test_data3[0])

In [36]:
print(Test_df_D1.shape)
print(Test_df_D2.shape)
print(Test_df_D3.shape)

(1436, 183)
(1436, 183)
(1436, 183)


In [37]:
Test_df_D1.head(1)

channel_0_0  channel_0_1  channel_0_2  channel_0_3  channel_0_4  \
0     0.043915     0.033922     0.007255    -0.030362    -0.069213   

   channel_0_5  channel_0_6  channel_0_7  channel_0_8  channel_0_9  ...  \
0    -0.101034    -0.123061    -0.138499    -0.153547    -0.173622  ...   

   channel_0_173  channel_0_174  channel_0_175  channel_0_176  channel_0_177  \
0            NaN            NaN            NaN            NaN            NaN   

   channel_0_178  channel_0_179  channel_0_180  channel_0_181  target  
0            NaN            NaN            NaN            NaN    b'1'  

[1 rows x 183 columns]

In [38]:
Test_df_D1.target.unique()

array([b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9', b'10', b'11',
       b'12', b'13', b'14', b'15', b'16', b'17', b'18', b'19', b'20'],
      dtype=object)

In [39]:
Test_df_D2.head(1)

channel_1_0  channel_1_1  channel_1_2  channel_1_3  channel_1_4  \
0    -0.010011    -0.004357     0.005951     0.018295     0.029589   

   channel_1_5  channel_1_6  channel_1_7  channel_1_8  channel_1_9  ...  \
0     0.038164     0.044259     0.048942     0.052885     0.056265  ...   

   channel_1_173  channel_1_174  channel_1_175  channel_1_176  channel_1_177  \
0            NaN            NaN            NaN            NaN            NaN   

   channel_1_178  channel_1_179  channel_1_180  channel_1_181  target  
0            NaN            NaN            NaN            NaN    b'1'  

[1 rows x 183 columns]

In [40]:
Test_df_D3.head(1)

channel_2_0  channel_2_1  channel_2_2  channel_2_3  channel_2_4  \
0     0.536491      0.76718     0.993862     1.184721      1.31248   

   channel_2_5  channel_2_6  channel_2_7  channel_2_8  channel_2_9  ...  \
0     1.360485      1.32964     1.241397      1.13202      1.03714  ...   

   channel_2_173  channel_2_174  channel_2_175  channel_2_176  channel_2_177  \
0            NaN            NaN            NaN            NaN            NaN   

   channel_2_178  channel_2_179  channel_2_180  channel_2_181  target  
0            NaN            NaN            NaN            NaN    b'1'  

[1 rows x 183 columns]

In [41]:
Test_df_D1_T = Test_df_D1.head(1).T
Test_df_D2_T = Test_df_D2.head(1).T
Test_df_D3_T = Test_df_D3.head(1).T

In [42]:
Test_df_D1_T=Test_df_D1_T.fillna(0)
Test_df_D2_T=Test_df_D2_T.fillna(0)
Test_df_D3_T=Test_df_D2_T.fillna(0)

In [43]:
Test_arr1 = Test_df_D1_T.to_numpy()
Test_arr2 = Test_df_D2_T.to_numpy()
Test_arr3 = Test_df_D3_T.to_numpy()

In [44]:
finalarray_test_data = np.concatenate((Test_arr1, Test_arr2),axis=1)

In [45]:
finalarray_test_data = np.concatenate((finalarray_test_data, Test_arr3),axis=1)

In [46]:
Origianl_test_view = finalarray_test_data

In [47]:
Origianl_test_view

array([[0.043915, -0.010011, -0.010011],
       [0.033922, -0.004357, -0.004357],
       [0.007255, 0.005951, 0.005951],
       [-0.030362, 0.018295, 0.018295],
       [-0.069213, 0.029589, 0.029589],
       [-0.101034, 0.038164, 0.038164],
       [-0.123061, 0.044259, 0.044259],
       [-0.138499, 0.048942, 0.048942],
       [-0.153547, 0.052885, 0.052885],
       [-0.173622, 0.056265, 0.056265],
       [-0.201387, 0.059159, 0.059159],
       [-0.236853, 0.061321, 0.061321],
       [-0.278391, 0.061678, 0.061678],
       [-0.323717, 0.058629, 0.058629],
       [-0.370581, 0.05106, 0.05106],
       [-0.417049, 0.038811, 0.038811],
       [-0.461461, 0.022059, 0.022059],
       [-0.502443, 0.000726, 0.000726],
       [-0.539417, -0.025113, -0.025113],
       [-0.573203, -0.054538, -0.054538],
       [-0.605837, -0.085954, -0.085954],
       [-0.639575, -0.117873, -0.117873],
       [-0.676042, -0.149349, -0.149349],
       [-0.716054, -0.179872, -0.179872],
       [-0.75975, -0.209258, 

# Random Time Series

For creating RTS, the start and end point, will take from test data view and in between the points would be random from Training Data

In [48]:
Starting_point = Origianl_test_view[:][0:1]
End_point = Origianl_test_view[:][182:183]

In [49]:
copy_of_training_view = finalarray_training_data

In [87]:
training_slice_1 = copy_of_training_view[:][1:46]
training_slice_2 = copy_of_training_view[:][46:92]
training_slice_3 = copy_of_training_view[:][92:135]
training_slice_4 = copy_of_training_view[:][135:182]

In [88]:
print(training_slice_1.shape)
print(training_slice_2.shape)
print(training_slice_3.shape)
print(training_slice_4.shape)

(45, 3)
(46, 3)
(43, 3)
(47, 3)


In [89]:
Random_Psuedo_Series = np.concatenate((Starting_point, training_slice_1),axis=0)
Random_Psuedo_Series = np.concatenate((Random_Psuedo_Series, training_slice_4),axis=0)
Random_Psuedo_Series = np.concatenate((Random_Psuedo_Series, training_slice_3),axis=0)
Random_Psuedo_Series = np.concatenate((Random_Psuedo_Series, training_slice_2),axis=0)
Random_Psuedo_Series = np.concatenate((Random_Psuedo_Series, End_point),axis=0)

In [90]:
Random_Psuedo_Series

array([[0.043915, -0.010011, -0.010011],
       [-0.183121, 0.083973, 1.157239],
       [-0.234104, 0.085534, 1.320469],
       [-0.279929, 0.078218, 1.369472],
       [-0.321851, 0.067093, 1.323889],
       [-0.363783, 0.05552, 1.221704],
       [-0.4095, 0.043275, 1.098215],
       [-0.460814, 0.027787, 0.979016],
       [-0.517526, 0.005932, 0.880755],
       [-0.57844, -0.025043, 0.806413],
       [-0.642335, -0.066984, 0.742138],
       [-0.708369, -0.120483, 0.670647],
       [-0.776037, -0.185363, 0.589337],
       [-0.844799, -0.261646, 0.509148],
       [-0.913359, -0.349528, 0.440515],
       [-0.978872, -0.448135, 0.3894],
       [-1.036865, -0.554524, 0.359572],
       [-1.082398, -0.663956, 0.344563],
       [-1.111614, -0.770916, 0.322058],
       [-1.122168, -0.870061, 0.271962],
       [-1.112322, -0.95681, 0.199647],
       [-1.080184, -1.027564, 0.130489],
       [-1.024236, -1.079644, 0.084365],
       [-0.944604, -1.111149, 0.064815],
       [-0.843469, -1.121016, 0

In [91]:
Random_Psuedo_Series.shape

(183, 3)

# Partial Psuedo TS

# Calculating DTW

In [122]:
import numpy as np
from scipy.spatial.distance import *

from fastdtw import fastdtw

In [123]:
OV = Origianl_test_view
RV = Random_Psuedo_Series

In [136]:
# RV.ndim
# np.info(RV)

In [137]:
distance, path = fastdtw(OV, RV, dist=jaccard)
print(distance)

181.0


In [ ]:
jaccard
euclidean
hamming
sqeuclidean
cityblock

# Single dimension code

In [102]:
# import numpy as np
# from dtw import dtw

In [104]:
# manhattan_distance = lambda Origianl_test_view, Random_Psuedo_Series: np.abs(Origianl_test_view - Random_Psuedo_Series)


In [106]:
# d, cost_matrix, acc_cost_matrix, path = dtw(Origianl_test_view, Random_Psuedo_Series, dist=manhattan_distance)

In [ ]:
# print(d)

# R Code

In [95]:
# import numpy as np
# import rpy2.robjects.numpy2ri

# rpy2.robjects.numpy2ri.activate()
# from rpy2.robjects.packages import importr
# import rpy2.robjects as robj


In [96]:
# R = rpy2.robjects.r

In [97]:
# dtw = importr("dtw")

In [98]:
# OV = Origianl_test_view
# RV = Random_Psuedo_Series

In [195]:
# # OV
# type(OV)

In [99]:
# rt,ct = Origianl_test_view.shape
# rq,cq = Random_Psuedo_Series.shape


# Origianl_test_view_R = R.matrix(OV,nrow=rt,ncol=ct)
# Random_Psuedo_Series_R = R.matrix(OV,nrow=rq,ncol=cq)

In [101]:
# # Calculate the alignment vector and corresponding distance
# Alignment = R.dtw(Origianl_test_view_R,Random_Psuedo_Series_R
#                   ,keep=True, step_pattern=R.rabinerJuangStepPattern(4,"c")
#                   ,open_begin=True,open_end=True
# )

In [194]:
# dist = Alignment.rx('distance')[0][0]