In [157]:
import numpy as np 
from scipy.io import arff
import pandas as pd

# Creating Training Data view

In [158]:
data1 = arff.loadarff('/Users/arslanaliawan/Desktop/Pre-experiment/Multivariate_arff/CharacterTrajectories/CharacterTrajectoriesDimension1_TRAIN.arff')

In [159]:
df_D1 = pd.DataFrame(data1[0])

In [160]:
data2 = arff.loadarff('/Users/arslanaliawan/Desktop/Pre-experiment/Multivariate_arff/CharacterTrajectories/CharacterTrajectoriesDimension2_TRAIN.arff')

In [161]:
df_D2 = pd.DataFrame(data2[0])

In [162]:
data3 = arff.loadarff('/Users/arslanaliawan/Desktop/Pre-experiment/Multivariate_arff/CharacterTrajectories/CharacterTrajectoriesDimension3_TRAIN.arff')

In [163]:
df_D3 = pd.DataFrame(data3[0])

In [164]:
print(df_D1.shape)
print(df_D2.shape)
print(df_D3.shape)

(1422, 183)
(1422, 183)
(1422, 183)


In [165]:
df_D1 =df_D1.apply(lambda x : x.fillna(method='ffill'), axis=1) 
df_D2 =df_D2.apply(lambda x : x.fillna(method='ffill'), axis=1)
df_D3 =df_D3.apply(lambda x : x.fillna(method='ffill'), axis=1) 

In [166]:
df_D1 = df_D1.drop('target', axis=1)
df_D2 = df_D2.drop('target', axis=1)
df_D3 = df_D3.drop('target', axis=1)

In [167]:
print(df_D1.shape)
print(df_D2.shape)
print(df_D3.shape)

(1422, 182)
(1422, 182)
(1422, 182)


In [168]:
df_D1.head(1)

channel_0_0  channel_0_1  channel_0_2  channel_0_3  channel_0_4  \
0     -0.13015    -0.183121    -0.234104    -0.279929    -0.321851   

   channel_0_5  channel_0_6  channel_0_7  channel_0_8  channel_0_9  ...  \
0    -0.363783      -0.4095    -0.460814    -0.517526     -0.57844  ...   

   channel_0_172  channel_0_173  channel_0_174  channel_0_175  channel_0_176  \
0       0.673591       0.673591       0.673591       0.673591       0.673591   

   channel_0_177  channel_0_178  channel_0_179  channel_0_180  channel_0_181  
0       0.673591       0.673591       0.673591       0.673591       0.673591  

[1 rows x 182 columns]

In [169]:
df_D1_T = df_D1.head(1).T
df_D2_T = df_D2.head(1).T
df_D3_T = df_D3.head(1).T

In [170]:
df_D1_T

0
channel_0_0   -0.130150
channel_0_1   -0.183121
channel_0_2   -0.234104
channel_0_3   -0.279929
channel_0_4   -0.321851
...                 ...
channel_0_177  0.673591
channel_0_178  0.673591
channel_0_179  0.673591
channel_0_180  0.673591
channel_0_181  0.673591

[182 rows x 1 columns]

In [171]:
arr1 = df_D1_T.to_numpy()
arr2 = df_D2_T.to_numpy()
arr3 = df_D3_T.to_numpy()

In [172]:
arr1

array([[-0.13015 ],
       [-0.183121],
       [-0.234104],
       [-0.279929],
       [-0.321851],
       [-0.363783],
       [-0.4095  ],
       [-0.460814],
       [-0.517526],
       [-0.57844 ],
       [-0.642335],
       [-0.708369],
       [-0.776037],
       [-0.844799],
       [-0.913359],
       [-0.978872],
       [-1.036865],
       [-1.082398],
       [-1.111614],
       [-1.122168],
       [-1.112322],
       [-1.080184],
       [-1.024236],
       [-0.944604],
       [-0.843469],
       [-0.724226],
       [-0.590649],
       [-0.446936],
       [-0.297932],
       [-0.148794],
       [-0.004546],
       [ 0.13014 ],
       [ 0.251447],
       [ 0.357344],
       [ 0.4482  ],
       [ 0.526596],
       [ 0.596567],
       [ 0.662582],
       [ 0.728357],
       [ 0.795736],
       [ 0.864318],
       [ 0.932146],
       [ 0.996691],
       [ 1.055067],
       [ 1.103557],
       [ 1.137583],
       [ 1.152673],
       [ 1.145736],
       [ 1.115602],
       [ 1.062653],


In [173]:
finalarray_training_data = np.concatenate((arr1, arr2),axis=1)

In [174]:
finalarray_training_data

array([[-0.13015 ,  0.071323],
       [-0.183121,  0.083973],
       [-0.234104,  0.085534],
       [-0.279929,  0.078218],
       [-0.321851,  0.067093],
       [-0.363783,  0.05552 ],
       [-0.4095  ,  0.043275],
       [-0.460814,  0.027787],
       [-0.517526,  0.005932],
       [-0.57844 , -0.025043],
       [-0.642335, -0.066984],
       [-0.708369, -0.120483],
       [-0.776037, -0.185363],
       [-0.844799, -0.261646],
       [-0.913359, -0.349528],
       [-0.978872, -0.448135],
       [-1.036865, -0.554524],
       [-1.082398, -0.663956],
       [-1.111614, -0.770916],
       [-1.122168, -0.870061],
       [-1.112322, -0.95681 ],
       [-1.080184, -1.027564],
       [-1.024236, -1.079644],
       [-0.944604, -1.111149],
       [-0.843469, -1.121016],
       [-0.724226, -1.109332],
       [-0.590649, -1.077545],
       [-0.446936, -1.028084],
       [-0.297932, -0.963634],
       [-0.148794, -0.886796],
       [-0.004546, -0.800359],
       [ 0.13014 , -0.707551],
       [

In [175]:
finalarray_training_dataV = np.concatenate((finalarray_training_data, arr3),axis=1)

In [176]:
finalarray_training_dataV

array([[-1.301500e-01,  7.132300e-02,  8.993060e-01],
       [-1.831210e-01,  8.397300e-02,  1.157239e+00],
       [-2.341040e-01,  8.553400e-02,  1.320469e+00],
       [-2.799290e-01,  7.821800e-02,  1.369472e+00],
       [-3.218510e-01,  6.709300e-02,  1.323889e+00],
       [-3.637830e-01,  5.552000e-02,  1.221704e+00],
       [-4.095000e-01,  4.327500e-02,  1.098215e+00],
       [-4.608140e-01,  2.778700e-02,  9.790160e-01],
       [-5.175260e-01,  5.932000e-03,  8.807550e-01],
       [-5.784400e-01, -2.504300e-02,  8.064130e-01],
       [-6.423350e-01, -6.698400e-02,  7.421380e-01],
       [-7.083690e-01, -1.204830e-01,  6.706470e-01],
       [-7.760370e-01, -1.853630e-01,  5.893370e-01],
       [-8.447990e-01, -2.616460e-01,  5.091480e-01],
       [-9.133590e-01, -3.495280e-01,  4.405150e-01],
       [-9.788720e-01, -4.481350e-01,  3.894000e-01],
       [-1.036865e+00, -5.545240e-01,  3.595720e-01],
       [-1.082398e+00, -6.639560e-01,  3.445630e-01],
       [-1.111614e+00, -7.70

In [154]:
# # getting col


# replace_Val = 0
# i = 0
# NullValue = 'NaN'
# for i in range(181):
#     as_string = str(i)
#     VAR =  X['channel_0_' + as_string]
#     if np.isnan(VAR[0]):
#         as_integer = int(i)
#         VAR = VAR.replace([VAR[0]],replace_Val)
# #         VAR[0] = VAR[0]-1
#         print(VAR[0])
#     else:
#         replace_Val = VAR[0]
        
        
  